import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest';
import mongoose from 'mongoose'; import { MongoMemoryServer } from 'mongodb-memory-server';
vi.mock('@/lib/firebase/verify', () => ({ verifyFirebaseIdToken: vi.fn(), hasTokenVerificationConfig: true }));
import { verifyFirebaseIdToken } from '@/lib/firebase/verify';
import { Client } from '@modelcontextprotocol/sdk/client/index.js'; import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { connectDB } from '@/lib/core/db'; import { resetConfigCacheForTests } from '@/lib/core/config'; import { provisionAccount } from '@/lib/accounts/service'; import { createAgent, createPairingCode, redeemPairingCode } from '@/lib/connections/service'; import { submitHandoffValues } from '@/lib/handoff/service'; import { buildMcpServer } from '@/lib/mcp/server';
import { POST as create, GET as list } from '@/app/v1/handoffs/route'; import { POST as decrypt } from '@/app/v1/handoffs/decrypt/route'; import { POST as close } from '@/app/v1/handoffs/close/route'; import { POST as status } from '@/app/v1/handoffs/status/route'; import { GET as ownerList } from '@/app/api/handoffs/route'; import { DELETE as ownerDelete } from '@/app/api/handoffs/[id]/route';
import Account from '@/models/Account'; import Agent from '@/models/Agent'; import Connection from '@/models/Connection'; import PairingCode from '@/models/PairingCode'; import Handoff from '@/models/Handoff'; import RateLimitBucket from '@/models/RateLimitBucket';
let server: MongoMemoryServer; const mockedVerify = vi.mocked(verifyFirebaseIdToken); const fields = [{ name: 'email', label: 'Email', type: 'email' as const, required: true }];
const req = (url: string, token?: string, body?: unknown) => new Request(url, { method: 'POST', headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
async function setup() { const account = await provisionAccount({ uid: 'handoff-owner', email: null, displayName: null, photoURL: null }); await Account.updateOne({ accountId: account.accountId }, { $set: { plan: 'plus' } }); const a = await createAgent(account, { name: 'A' }); const b = await createAgent(account, { name: 'B' }); const ca = await createPairingCode(account, a.agentId, {}); const cb = await createPairingCode(account, b.agentId, {}); const one = await redeemPairingCode({ code: ca.code }); const two = await redeemPairingCode({ code: cb.code }); return { account, one, two }; }
beforeAll(async()=>{server=await MongoMemoryServer.create();process.env.MONGODB_URI=server.getUri();resetConfigCacheForTests();await connectDB();await Promise.all([Account.createIndexes(),Agent.createIndexes(),Connection.createIndexes(),PairingCode.createIndexes(),Handoff.createIndexes(),RateLimitBucket.createIndexes()]);}); afterEach(async()=>{vi.clearAllMocks();await Promise.all([Account.deleteMany({}),Agent.deleteMany({}),Connection.deleteMany({}),PairingCode.deleteMany({}),Handoff.deleteMany({}),RateLimitBucket.deleteMany({})]);}); afterAll(async()=>{await mongoose.disconnect();await server.stop();resetConfigCacheForTests();});
describe('handoff v1 contracts',()=>{
 it('requires connection authentication',async()=>{const r=await create(req('http://localhost/v1/handoffs') as never);expect(r.status).toBe(401);expect((await r.json()).error.code).toBe('authentication_required');});
 it('creates, lists, decrypts creator values, polls and done-closes',async()=>{const {one,two}=await setup();const made=await create(req('http://localhost/v1/handoffs',one.credential,{fieldSchema:fields,title:'Login'}) as never);expect(made.status).toBe(201);const body=await made.json();expect(body).toMatchObject({data:{handoffId:expect.stringMatching(/^cv_/),viewToken:expect.stringMatching(/^htv_/),submitToken:expect.stringMatching(/^hts_/)},request_id:expect.stringMatching(/^req_/)});await submitHandoffValues(body.data.submitToken,{email:'a@b.com'});const values=await decrypt(req('http://localhost/v1/handoffs/decrypt',one.credential,{handoffId:body.data.handoffId}) as never);expect(values.status).toBe(200);expect((await values.json()).data).toEqual({email:'a@b.com'});const denied=await decrypt(req('http://localhost/v1/handoffs/decrypt',two.credential,{handoffId:body.data.handoffId}) as never);expect(denied.status).toBe(404);expect((await denied.json()).error.code).toBe('not_found');const polled=await status(req('http://localhost/v1/handoffs/status',two.credential,{handoffId:body.data.handoffId}) as never);const poll=await polled.json();expect(polled.status).toBe(200);expect(poll.data).toMatchObject({handoffId:body.data.handoffId,status:'submitted'});expect(JSON.stringify(poll)).not.toMatch(/token|ciphertext|email/i);const listed=await list(new Request('http://localhost/v1/handoffs',{headers:{authorization:`Bearer ${one.credential}`}}) as never);expect(listed.status).toBe(200);expect(JSON.stringify(await listed.json())).not.toMatch(/token|ciphertext|fieldSchema/i);const closed=await close(req('http://localhost/v1/handoffs/close',one.credential,{handoffId:body.data.handoffId,reason:'done'}) as never);expect(closed.status).toBe(200);expect((await closed.json()).data).toEqual({closed:true});});
 it('owner lists metadata and revokes without any decrypt surface',async()=>{const {account,one}=await setup();const made=await create(req('http://localhost/v1/handoffs',one.credential,{fieldSchema:fields}) as never);const handoffId=(await made.json()).data.handoffId;mockedVerify.mockResolvedValue({uid:'handoff-owner'});const listed=await ownerList(new Request('http://localhost/api/handoffs',{headers:{authorization:'Bearer owner'}}) as never);expect(listed.status).toBe(200);expect(JSON.stringify(await listed.json())).not.toMatch(/token|ciphertext|fieldSchema/i);mockedVerify.mockResolvedValue({uid:'handoff-owner'});const revoked=await ownerDelete(new Request(`http://localhost/api/handoffs/${handoffId}`,{method:'DELETE',headers:{authorization:'Bearer owner'}}) as never,{params:Promise.resolve({id:handoffId})});expect(revoked.status).toBe(200);expect((await revoked.json()).data).toEqual({revoked:true});expect(account.accountId).toBeTruthy();});
 it('exposes registry handoff tools only to a connection and polls through MCP',async()=>{const {one}=await setup();const actor={connectionId:one.connection.connectionId,agentId:one.connection.agentId,accountId:one.connection.accountId};const server=buildMcpServer(actor);const client=new Client({name:'test',version:'1'});const [ct,st]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(st),client.connect(ct)]);const names=(await client.listTools()).tools.map(x=>x.name);expect(names).toEqual(expect.arrayContaining(['pair_connection','connection_status','handoff_create','handoff_decrypt','handoff_close','handoff_status']));const made=await client.callTool({name:'handoff_create',arguments:{fieldSchema:fields}});const data=JSON.parse(((made.content as Array<{text:string}>)[0] as {text:string}).text).data;const polled=await client.callTool({name:'handoff_status',arguments:{handoffId:data.handoffId}});expect(JSON.parse(((polled.content as Array<{text:string}>)[0] as {text:string}).text).data.status).toBe('awaiting');const publicServer=buildMcpServer(undefined);const publicClient=new Client({name:'public',version:'1'});const [pct,pst]=InMemoryTransport.createLinkedPair();await Promise.all([publicServer.connect(pst),publicClient.connect(pct)]);expect((await publicClient.listTools()).tools.map(x=>x.name)).toEqual(['pair_connection']);});
});
