import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import mongoose from 'mongoose'; import { MongoMemoryServer } from 'mongodb-memory-server'; import { renderToStaticMarkup } from 'react-dom/server';
import { connectDB } from '@/lib/core/db'; import { resetConfigCacheForTests } from '@/lib/core/config'; import { provisionAccount } from '@/lib/accounts/service'; import Handoff from '@/models/Handoff'; import Account from '@/models/Account'; import Activity from '@/models/Activity'; import RateLimitBucket from '@/models/RateLimitBucket';
import { createHandoff, decryptHandoff, submitHandoffValues, type ConnectionActor, viewHandoffForForm } from '@/lib/handoff/service'; import { POST } from '@/app/api/handoff-submit/route'; import Page from '@/app/h/[id]/page';
let server: MongoMemoryServer; const now = new Date(); const fields=[{name:'email',label:'Email',type:'email' as const,required:true,prefill:'known@example.com'},{name:'password',label:'Password',type:'password' as const,required:true}]; const values={email:'person@example.com',password:'secret'};
beforeAll(async()=>{server=await MongoMemoryServer.create();process.env.MONGODB_URI=server.getUri();resetConfigCacheForTests();await connectDB();await Promise.all([Account.createIndexes(),Handoff.createIndexes(),Activity.createIndexes(),RateLimitBucket.createIndexes()]);}); afterEach(async()=>{await Promise.all([Account.deleteMany({}),Handoff.deleteMany({}),Activity.deleteMany({}),RateLimitBucket.deleteMany({})]);}); afterAll(async()=>{await mongoose.disconnect();await server.stop();resetConfigCacheForTests();});
async function actor():Promise<ConnectionActor>{const a=await provisionAccount({uid:`u${Math.random()}`,email:null,displayName:null,photoURL:null});return {accountId:a.accountId,agentId:'agent_test',connectionId:'conn_test'};} async function made(a:ConnectionActor){return createHandoff(a,{fieldSchema:fields,title:'Credentials'},{now});} function request(h:{handoffId:string;viewToken:string}, body:object, ip='203.0.113.4'){return POST(new Request('http://localhost/api/handoff-submit',{method:'POST',headers:{'content-type':'application/json','x-forwarded-for':ip},body:JSON.stringify({handoffId:h.handoffId,token:h.viewToken,website:'',...body})}));}
describe('public handoff form',()=>{
 it('returns public metadata only and makes password prefill absent',async()=>{const h=await made(await actor());const form=await viewHandoffForForm(h.viewToken,{now});expect(form.fields).toContainEqual(expect.objectContaining({name:'email',prefill:'known@example.com'}));expect(form.fields.find(f=>f.name==='password')).not.toHaveProperty('prefill');expect(JSON.stringify(form)).not.toMatch(/token|hash/i);});
 it('uses the same not_found error for unknown expired and used form links',async()=>{const a=await actor(), expired=await made(a), used=await made(a);await submitHandoffValues(used.viewToken,values,{now});const errors=await Promise.all(['bogus',expired.viewToken,used.viewToken].map(async token=>{try{await viewHandoffForForm(token,{now:new Date(now.getTime()+2*3600_000)});}catch(error){const e=error as {code:string;message:string;http:number};return {code:e.code,message:e.message,http:e.http};}}));expect(errors).toEqual(Array(3).fill({code:'not_found',message:'The requested resource was not found.',http:404}));});
 it('submits via possession URL and is decryptable',async()=>{const a=await actor(),h=await made(a);const response=await request(h,{values});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({data:{handoffId:h.handoffId,status:'submitted'},request_id:expect.any(String)});await expect(decryptHandoff(h.handoffId,a,{now})).resolves.toEqual(values);});
 it('blocks double submission',async()=>{const h=await made(await actor());expect((await request(h,{values})).status).toBe(200);expect((await request(h,{values})).status).toBe(404);});
 it('silently drops honeypots and records an activity',async()=>{const h=await made(await actor());const response=await request(h,{values,website:'bot'});expect(response.status).toBe(200);expect(await Handoff.findOne({handoffId:h.handoffId}).lean()).toMatchObject({status:'awaiting'});expect(await Activity.findOne({handoffId:h.handoffId,event:'handoff.honeypot_tripped'}).lean()).not.toBeNull();});
 it('keeps token usable after a required-field validation failure',async()=>{const h=await made(await actor());expect((await request(h,{values:{email:'person@example.com',password:''}})).status).toBe(422);expect((await request(h,{values})).status).toBe(200);});
 it('rate limits the eleventh IP submission',async()=>{const a=await actor();const handoffs=await Promise.all(Array.from({length:11},()=>made(a)));for(const h of handoffs.slice(0,10)) expect((await request(h,{values},'198.51.100.1')).status).toBe(200);expect((await request(handoffs[10],{values},'198.51.100.1')).status).toBe(429);});
 it('renders byte-identical neutral terminal state for invalid and expired links',async()=>{const h=await createHandoff(await actor(),{fieldSchema:fields,title:'Credentials'},{now:new Date(Date.now()-2*3600_000)});const unknown=renderToStaticMarkup(await Page({params:Promise.resolve({id:'cv_nope'}),searchParams:Promise.resolve({t:'bogus'})}));const expired=renderToStaticMarkup(await Page({params:Promise.resolve({id:h.handoffId}),searchParams:Promise.resolve({t:h.viewToken})}));expect(unknown).toBe(expired);expect(unknown).toContain('This link is no longer available');expect(unknown).not.toMatch(/token|credential/i);});
});
