import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import mongoose from 'mongoose'; import { MongoMemoryServer } from 'mongodb-memory-server';
import { connectDB } from '@/lib/core/db'; import { resetConfigCacheForTests } from '@/lib/core/config'; import { provisionAccount } from '@/lib/accounts/service'; import { authenticateConnection, createAgent, createPairingCode, redeemPairingCode, renameAgent, revokeConnection } from '@/lib/connections/service'; import Account from '@/models/Account'; import Agent from '@/models/Agent'; import Connection from '@/models/Connection'; import PairingCode from '@/models/PairingCode'; import RateLimitBucket from '@/models/RateLimitBucket';
let server: MongoMemoryServer;
beforeAll(async()=>{server=await MongoMemoryServer.create();process.env.MONGODB_URI=server.getUri();resetConfigCacheForTests();await connectDB();await Promise.all([Account.createIndexes(),Agent.createIndexes(),Connection.createIndexes(),PairingCode.createIndexes(),RateLimitBucket.createIndexes()]);}); afterEach(async()=>{await Promise.all([Account.deleteMany({}),Agent.deleteMany({}),Connection.deleteMany({}),PairingCode.deleteMany({}),RateLimitBucket.deleteMany({})]);});afterAll(async()=>{await mongoose.disconnect();await server.stop();resetConfigCacheForTests();});
async function account(uid='u'){return provisionAccount({uid,email:null,displayName:null,photoURL:null});}
describe('connections service',()=>{it('creates, renames and isolates agents',async()=>{const a=await account('a'),b=await account('b');const agent=await createAgent(a,{name:'  My Agent  '});expect(agent.name).toBe('My Agent');await expect(createAgent(a,{name:'My Agent'})).rejects.toMatchObject({code:'validation_failed'});await expect(renameAgent(b,agent.agentId,{name:'No'})).rejects.toMatchObject({code:'not_found'});await expect(renameAgent(a,agent.agentId,{name:'Renamed'})).resolves.toMatchObject({name:'Renamed'});});
it('round trips a pairing credential and authenticates it',async()=>{const a=await account();const agent=await createAgent(a,{name:'One'});const pair=await createPairingCode(a,agent.agentId,{runtime:'node'});const redeemed=await redeemPairingCode({code:pair.code,runtimeVersion:'1.2'});expect(redeemed.credential).toMatch(/^au_conn_/);await expect(authenticateConnection(redeemed.credential)).resolves.toMatchObject({accountId:a.accountId,agentId:agent.agentId});});
it('permits exactly one concurrent redemption',async()=>{const a=await account();const agent=await createAgent(a,{name:'One'});const {code}=await createPairingCode(a,agent.agentId,{});const result=await Promise.allSettled([redeemPairingCode({code}),redeemPairingCode({code})]);expect(result.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(result.filter(x=>x.status==='rejected')[0]).toMatchObject({reason:{code:'not_found'}});});
it('rejects expired codes uniformly',async()=>{const a=await account();const agent=await createAgent(a,{name:'One'});const now=new Date('2026-01-01');const {code}=await createPairingCode(a,agent.agentId,{}, {now});await expect(redeemPairingCode({code},{now:new Date(now.getTime()+660000)})).rejects.toMatchObject({code:'not_found'});});
it('enforces free capacity and releases the pairing code after capacity failure',async()=>{const a=await account();const agent=await createAgent(a,{name:'One'});const p1=await createPairingCode(a,agent.agentId,{});await redeemPairingCode({code:p1.code});const p2=await createPairingCode(a,agent.agentId,{});await expect(redeemPairingCode({code:p2.code})).rejects.toMatchObject({code:'plan_limit_reached'});expect(await PairingCode.findOne({codeHash: (await import('@/lib/core/secrets')).hashSecret(p2.code)}).lean()).toMatchObject({redeemedAt:null});});
it('maps revoked and suspended actors to documented errors',async()=>{const a=await account();const agent=await createAgent(a,{name:'One'});const p=await createPairingCode(a,agent.agentId,{});const {credential,connection}=await redeemPairingCode({code:p.code});await revokeConnection(a,connection.connectionId);await expect(authenticateConnection(credential)).rejects.toMatchObject({code:'connection_revoked'});const p2=await createPairingCode(a,agent.agentId,{});await Account.updateOne({accountId:a.accountId},{$set:{status:'suspended'}});await expect(redeemPairingCode({code:p2.code})).rejects.toMatchObject({code:'not_found'});});});
