'use client';
import { useState } from 'react';
type Review = { summary: string; concerns: string[]; confidence: number; context: unknown; status: string };
export default function ConfessionResponseForm({ id }: { id: string }) {
  const [credential, setCredential] = useState(''), [keyType, setKeyType] = useState<'approval' | 'admin'>('approval'), [review, setReview] = useState<Review | null>(null), [guidance, setGuidance] = useState(''), [action, setAction] = useState('continue'), [message, setMessage] = useState('');
  const headers = () => ({ 'content-type': 'application/json', [keyType === 'admin' ? 'x-admin-key' : 'x-approval-key']: credential });
  async function unlock(e: React.FormEvent) { e.preventDefault(); setMessage('Authenticating…'); const res = await fetch(`/v1/confessions/${encodeURIComponent(id)}/review`, { headers: headers() }); if (!res.ok) return setMessage(`Unable to authenticate (${res.status}).`); const json = await res.json(); setReview(json.data); setMessage(''); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setMessage('Submitting…'); const res = await fetch(`/v1/confessions/${encodeURIComponent(id)}/respond`, { method: 'POST', headers: headers(), body: JSON.stringify({ guidance, action }) }); setMessage(res.ok ? 'Guidance submitted. The agent can now poll for it.' : `Unable to submit (${res.status}). Check the credential and fields.`); }
  if (!review) return <form onSubmit={unlock} className="mt-8 space-y-4"><label className="block text-sm">Credential type<select value={keyType} onChange={e => setKeyType(e.target.value as 'approval' | 'admin')} className="mt-1 w-full rounded border p-2 text-black"><option value="approval">Approval-proxy key</option><option value="admin">Admin key</option></select></label><label className="block text-sm">Credential<input required type="password" value={credential} onChange={e => setCredential(e.target.value)} className="mt-1 w-full rounded border p-2 text-black" autoComplete="off" /></label><button className="rounded bg-blue-600 px-4 py-2 text-white" type="submit">Review confession</button>{message && <p role="status">{message}</p>}</form>;
  return <><h1 className="mt-2 text-3xl font-bold">{review.summary}</h1><p className="mt-3">Status: <strong>{review.status}</strong> · Confidence: {review.confidence}</p><h2 className="mt-7 text-xl font-semibold">Concerns</h2><ul className="mt-2 list-disc space-y-1 pl-5">{review.concerns.map(c => <li key={c}>{c}</li>)}</ul>{review.context !== null && <pre className="mt-4 overflow-auto rounded bg-gray-100 p-4 text-sm text-black">{JSON.stringify(review.context, null, 2)}</pre>}<form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm">Guidance<textarea required value={guidance} onChange={e => setGuidance(e.target.value)} className="mt-1 w-full rounded border p-2 text-black" rows={4} /></label><label className="block text-sm">Action<select value={action} onChange={e => setAction(e.target.value)} className="mt-1 w-full rounded border p-2 text-black"><option value="continue">Continue</option><option value="pivot">Pivot</option><option value="abort">Abort</option></select></label><button className="rounded bg-blue-600 px-4 py-2 text-white" type="submit">Send guidance</button>{message && <p role="status">{message}</p>}</form></>;
}
